# Generated by Django 2.2.1 on 2019-06-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_due', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
    ]
